In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import numpy as np

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
addition = A + B
print("Addition:\n", addition)

# Subtraction
subtraction = A - B
print("Subtraction:\n", subtraction)

# Multiplication (element-wise)
elementwise_multiplication = A * B
print("Element-wise Multiplication:\n", elementwise_multiplication)

# Matrix Multiplication (dot product)
matrix_multiplication = np.dot(A, B)
print("Matrix Multiplication:\n", matrix_multiplication)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [ ]:
# Transpose of a matrix
transpose = A.T
print("Transpose:\n", transpose)


Transpose:
 [[1 3]
 [2 4]]


In [ ]:
# Determinant of a Matrix A
det = np.linalg.det(A)
print("Determinant\n", det)

Determinant
 -2.0000000000000004


In [ ]:
# Rank of Matrix A
# Find the number of linearly independent rows or columns in matrix
rank = np.linalg.matrix_rank(A)
print("Rank\n", rank)

Rank
 2


Vector Normalization
Definition:

Vector normalization is the process of scaling a vector to have a length (or magnitude) of 1, while preserving its direction. This normalized vector is often referred to as a unit vector.

Formula:

Given a vector v = (v₁, v₂, ..., vₙ), its normalized form v̂ is calculated as follows:

v̂ = v / ||v||

where ||v|| represents the magnitude (or Euclidean norm) of the vector v, calculated as:

||v|| = √(v₁² + v₂² + ... + vₙ²)

Edge Cases:

Zero Vector: If the input vector is a zero vector (all elements are 0), its magnitude is 0. In this case, normalization is undefined as it would involve division by zero. A common practice is to return the zero vector itself as the normalized vector in this scenario.

Vectors with Very Small Magnitude: If the vector has a very small magnitude, normalization can lead to numerical instability due to potential division by a very small number. It's important to be aware of this and handle such cases appropriately, potentially by setting a threshold for the minimum magnitude before performing normalization.

Example:

Consider the vector v = (3, 4).

Calculate the magnitude: ||v|| = √(3² + 4²) = 5

Normalize the vector: v̂ = (3/5, 4/5) = (0.6, 0.8)

The resulting vector v̂ has a magnitude of 1 and points in the same direction as the original vector v.

Applications:

Vector normalization is widely used in various fields, including:

Computer Graphics: Normalizing vectors is crucial for lighting calculations and surface normals.
Machine Learning: Normalizing features is often used to improve the performance of machine learning algorithms.
Data Analysis: Normalization can be applied to datasets to bring variables to a common scale.
Physics: Unit vectors are commonly used to represent directions, such as velocity and force.

In [ ]:
# prompt: What is vector normalization. give a pseudo code in the form of comments and then write code in python

import numpy as np

# Vector normalization pseudocode:
#
# Function normalize_vector(vector):
#   # Calculate the magnitude (Euclidean norm) of the vector.
#   # magnitude = sqrt(sum of squares of vector elements)
#
#   # Check if the magnitude is zero to prevent division by zero.
#   # If magnitude is zero:
#     # Return the zero vector (vector of the same shape with all elements as 0)
#
#   # Normalize each element of the vector by dividing it by its magnitude.
#   # normalized_vector = vector / magnitude
#
#   # Return the normalized vector

def normalize_vector(vector):
  """Normalizes a given vector.

  Args:
    vector: A NumPy array representing the vector.

  Returns:
    A NumPy array representing the normalized vector,
    or a zero vector if the input vector has zero magnitude.
  """
  magnitude = np.linalg.norm(vector)
  if magnitude == 0:
    return np.zeros_like(vector)
  return vector / magnitude

# Example usage
vector = np.array([1, 2, 3])
normalized_vector = normalize_vector(vector)
print("Original Vector:", vector)
print("Normalized Vector:", normalized_vector)

#Verification
print("Magnitude of normalized vector: ", np.linalg.norm(normalized_vector))

Original Vector: [1 2 3]
Normalized Vector: [0.26726124 0.53452248 0.80178373]
Magnitude of normalized vector:  1.0
